version: '3.8'
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PORT: ${DATABASE_PORT}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: 'bitnami/redis:latest'
    environment:
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DISABLE_COMMANDS: ${REDIS_DISABLE_COMMANDS}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
volumes:
  db:
    driver: local
